IF OBJECT_ID('Clientes', 'C') IS NULL
BEGIN
    CREATE TABLE Clientes(
	Id NVARCHAR(36) NOT NULL,
	Dni NVARCHAR(20) NOT NULL,
	Nombre NVARCHAR(100) NOT NULL,
	Apellidos NVARCHAR(150) NOT NULL,
	Email NVARCHAR(150) NOT NULL,
	FechaCreacion DATETIME2(7) NOT NULL,
	FechaModificacion DATETIME2(7) NULL);
END